steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_AR_HOSTNAME}/${PROJECT_ID}/${_PLATFORM_MANAGED_REPO}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${PROJECT_ID}/${_PLATFORM_MANAGED_REPO}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--platform=managed'
      - '--image=${_AR_HOSTNAME}/${PROJECT_ID}/${_PLATFORM_MANAGED_REPO}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_DEPLOY_REGION}'
      - '--quiet'
    entrypoint: gcloud

images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/${_PLATFORM_MANAGED_REPO}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
